"""Compare Fira Code and Source Han Mono glyph coverage to identify conflicting CIDs.

This script reads the JSON reports generated by fontIdentifierReport.py and:
1. Identifies all Unicode codepoints covered by Fira Code
2. Finds Source Han Mono CIDs that map to those same codepoints
3. Generates lists of CIDs to remove from Source Han Mono source files

Usage:
    python compare_font_coverage.py \
        --fira-code reports/font-identifiers/FiraCode-Regular.ttf.glyphIdentifiers.json \
        --source-han-mono reports/font-identifiers/SourceHanMono-Regular.otf.glyphIdentifiers.json \
        --output removal_list.txt
"""

import json
import argparse
from pathlib import Path
from typing import Set, Dict, List
from collections import defaultdict


def load_font_report(json_path: Path) -> dict:
    """Load a font identifier report JSON file."""
    with json_path.open('r', encoding='utf-8') as f:
        return json.load(f)


def extract_unicode_coverage(report: dict) -> Set[int]:
    """Extract all Unicode codepoints covered by a font."""
    unicode_set = set()
    for glyph in report['listGlyph']:
        unicode_set.update(glyph['listUnicodeScalarValue'])
    return unicode_set


def build_unicode_to_cid_map(report: dict) -> Dict[int, List[int]]:
    """Build a mapping from Unicode codepoint to Source Han Mono CIDs."""
    unicode_to_cids = defaultdict(list)
    for glyph in report['listGlyph']:
        source_han_cid = glyph.get('sourceHanMonoCid')
        if source_han_cid is not None:
            for unicode_value in glyph['listUnicodeScalarValue']:
                unicode_to_cids[unicode_value].append(source_han_cid)
    return dict(unicode_to_cids)


def identify_cids_to_remove(fira_unicode: Set[int], 
                            source_han_map: Dict[int, List[int]]) -> Set[int]:
    """Identify Source Han Mono CIDs that conflict with Fira Code coverage."""
    cids_to_remove = set()
    for unicode_value in fira_unicode:
        if unicode_value in source_han_map:
            cids_to_remove.update(source_han_map[unicode_value])
    return cids_to_remove


def format_unicode_range(unicode_values: Set[int]) -> List[str]:
    """Format Unicode values into readable ranges."""
    if not unicode_values:
        return []
    
    sorted_values = sorted(unicode_values)
    ranges = []
    start = sorted_values[0]
    prev = start
    
    for value in sorted_values[1:]:
        if value != prev + 1:
            if start == prev:
                ranges.append(f"U+{start:04X}")
            else:
                ranges.append(f"U+{start:04X}-U+{prev:04X}")
            start = value
        prev = value
    
    # Add the last range
    if start == prev:
        ranges.append(f"U+{start:04X}")
    else:
        ranges.append(f"U+{start:04X}-U+{prev:04X}")
    
    return ranges


def main():
    parser = argparse.ArgumentParser(
        description='Compare font coverage and identify CIDs to remove'
    )
    parser.add_argument(
        '--fira-code',
        type=Path,
        required=True,
        help='Path to Fira Code glyphIdentifiers.json report'
    )
    parser.add_argument(
        '--source-han-mono',
        type=Path,
        required=True,
        help='Path to Source Han Mono glyphIdentifiers.json report'
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=Path('cids_to_remove.txt'),
        help='Output file for CIDs to remove (default: cids_to_remove.txt)'
    )
    parser.add_argument(
        '--detailed',
        action='store_true',
        help='Generate detailed report with Unicode mappings'
    )
    
    args = parser.parse_args()
    
    # Load reports
    print(f"Loading Fira Code report: {args.fira_code}")
    fira_report = load_font_report(args.fira_code)
    
    print(f"Loading Source Han Mono report: {args.source_han_mono}")
    source_han_report = load_font_report(args.source_han_mono)
    
    # Extract coverage
    print("\nAnalyzing coverage...")
    fira_unicode = extract_unicode_coverage(fira_report)
    source_han_map = build_unicode_to_cid_map(source_han_report)
    
    print(f"Fira Code covers {len(fira_unicode)} Unicode codepoints")
    print(f"Source Han Mono has {len(source_han_report['listGlyph'])} glyphs")
    
    # Identify conflicts
    cids_to_remove = identify_cids_to_remove(fira_unicode, source_han_map)
    
    print(f"\nFound {len(cids_to_remove)} Source Han Mono CIDs that conflict with Fira Code")
    
    # Write output
    with args.output.open('w', encoding='utf-8') as f:
        f.write(f"# Source Han Mono CIDs to remove\n")
        f.write(f"# These CIDs map to Unicode codepoints covered by Fira Code\n")
        f.write(f"# Total: {len(cids_to_remove)} CIDs\n\n")
        
        for cid in sorted(cids_to_remove):
            f.write(f"{cid}\n")
    
    print(f"\nWrote CID removal list to: {args.output}")
    
    # Detailed report if requested
    if args.detailed:
        detailed_path = args.output.with_suffix('.detailed.txt')
        with detailed_path.open('w', encoding='utf-8') as f:
            f.write("# Detailed CID Removal Report\n\n")
            f.write(f"## Fira Code Unicode Coverage\n")
            f.write(f"Total codepoints: {len(fira_unicode)}\n\n")
            
            ranges = format_unicode_range(fira_unicode)
            for range_str in ranges:
                f.write(f"{range_str}\n")
            
            f.write(f"\n## Conflicting CIDs\n")
            f.write(f"Total: {len(cids_to_remove)}\n\n")
            
            # Group by Unicode codepoint
            conflicts = defaultdict(list)
            for unicode_value in fira_unicode:
                if unicode_value in source_han_map:
                    for cid in source_han_map[unicode_value]:
                        conflicts[cid].append(unicode_value)
            
            for cid in sorted(conflicts.keys()):
                unicode_list = [f"U+{u:04X}" for u in sorted(conflicts[cid])]
                f.write(f"CID {cid}: {', '.join(unicode_list)}\n")
        
        print(f"Wrote detailed report to: {detailed_path}")
    
    # Summary statistics
    print("\n" + "="*60)
    print("SUMMARY")
    print("="*60)
    print(f"Fira Code Unicode coverage: {len(fira_unicode)} codepoints")
    
    unicode_ranges = format_unicode_range(fira_unicode)
    print(f"Unicode ranges covered by Fira Code:")
    for range_str in unicode_ranges[:10]:  # Show first 10 ranges
        print(f"  {range_str}")
    if len(unicode_ranges) > 10:
        print(f"  ... and {len(unicode_ranges) - 10} more ranges")
    
    print(f"\nSource Han Mono CIDs to remove: {len(cids_to_remove)}")
    print(f"Remaining Source Han Mono glyphs: {source_han_report['glyphCount'] - len(cids_to_remove)}")


if __name__ == '__main__':
    main()
